version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.12"
  commands:
    - pip install ".[visualize]"
    - pip install pdoc3
    - pdoc --html --output-dir $READTHEDOCS_OUTPUT/html/ ecoscope_workflows
