[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]

[project]
name = "ecoscope_workflows"
dynamic = ["version"]
# requires-python = ">=3.9"
description = ""
readme = "README.md"
authors = [
  { name = "Charles Stern", email = "charless@earthranger.com" }
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: OS Independent",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
]
# license = { text = "" }
# keywords = []
dependencies = [
    "pandera",
    "pydantic",
    "ruamel.yaml"
]

[project.optional-dependencies]
test = [
    "ecoscope",
    "pytest",
]

[project.scripts]
ecoscope-workflows = "ecoscope_workflows.__main__:main"

[project.urls]
Homepage = "https://github.com/wildlife-dynamics/ecoscope-workflows"
Tracker = "https://github.com/wildlife-dynamics/ecoscope-workflows/issues"

[tool.setuptools_scm]
write_to = "ecoscope_workflows/_version.py"
write_to_template = "__version__ = '{version}'"

[tool.setuptools.package-data]
ecoscope_workflows = ["py.typed"]

[tool.isort]
# Prevent isort & black from fighting each other
profile = "black"
